INSERT INTO kayttajat VALUES (1, 'admin', 'passwd', true, true);
INSERT INTO kayttajat VALUES (2, 'normi', 'salasana', false, false);
INSERT INTO raakaaineet VALUES (1, 'kahvia');
INSERT INTO raakaaineet VALUES (2, 'viskiä');
INSERT INTO raakaaineet VALUES (3, 'vodkaa');
INSERT INTO raakaaineet VALUES (4, 'appelsiinimehua');
INSERT INTO raakaaineet VALUES (5, 'kahvilikööriä');
INSERT INTO raakaaineet VALUES (6, 'kermaa');
INSERT INTO raakaaineet VALUES (7, 'giniä');
INSERT INTO raakaaineet VALUES (8, 'greippilimonadia');