INSERT INTO kayttajat VALUES (1, 'admin', 'passwd', true, true);
INSERT INTO kayttajat VALUES (2, 'normi', 'salasana', false, false);
INSERT INTO raakaaineet VALUES (1, 'kahvia');
INSERT INTO raakaaineet VALUES (2, 'viskiä');
INSERT INTO raakaaineet VALUES (3, 'vodkaa');
INSERT INTO raakaaineet VALUES (4, 'appelsiinimehua');
INSERT INTO raakaaineet VALUES (5, 'kahvilikööriä');
INSERT INTO raakaaineet VALUES (6, 'kermaa');
INSERT INTO raakaaineet VALUES (7, 'giniä');
INSERT INTO raakaaineet VALUES (8, 'greippilimonadia');
INSERT INTO drinkit VALUES (1, 'Irish Coffee', NULL, 'Cocktail', 'sekoitetaan');
INSERT INTO muokkaajat VALUES (1, 1, '2014-09-18 12:00:00');
INSERT INTO ainesosat VALUES (10, 1, 1);
INSERT INTO ainesosat VALUES (4, 1, 2);
INSERT INTO drinkit VALUES (2, 'Screw Driver', NULL, 'Cocktail', 'tarjoillaan jäillä');
INSERT INTO muokkaajat VALUES (1, 1, '2014-09-26 12:00:00');
INSERT INTO ainesosat VALUES (4, 2, 3);
INSERT INTO ainesosat VALUES (10, 2, 4);
INSERT INTO drinkit VALUES (3, 'Valkovenäläinen', NULL, 'Cocktail', 'rakennetaan');
INSERT INTO muokkaajat VALUES (1, 1, '2014-09-28 12:00:00');
INSERT INTO ainesosat VALUES (2, 3, 3);
INSERT INTO ainesosat VALUES (2, 3, 5);
INSERT INTO ainesosat VALUES (2, 3, 6);
INSERT INTO drinkit VALUES (4, 'Lonkero', 'Gin Long Drink', 'Long drink', 'sekoitetaan');
INSERT INTO muokkaajat VALUES (1, 1, '2014-09-28 12:00:00');
INSERT INTO ainesosat VALUES (4, 4, 7);
INSERT INTO ainesosat VALUES (33, 4, 8);